# Generated by Django 3.0.3 on 2020-03-11 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_disease_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomcategory',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='symptom',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptomCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.SymptomCategory'),
        ),
        migrations.AddField(
            model_name='prescriptionfactors',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.FactorOptions'),
        ),
        migrations.AddField(
            model_name='prescriptionfactors',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Disease'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='factor',
            field=models.ManyToManyField(through='register_disease_data.PrescriptionFactors', to='register_disease_data.FactorOptions'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Medicine_Type_Usage'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathogen',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicinetype',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicinetakingway',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicinetakinginstruction',
            name='factors',
            field=models.ManyToManyField(through='register_disease_data.InstructionFactor', to='register_disease_data.FactorOptions'),
        ),
        migrations.AddField(
            model_name='medicinetakinginstruction',
            name='medicine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Medicine_Type_Usage'),
        ),
        migrations.AddField(
            model_name='medicine_type_usage',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Measurement'),
        ),
        migrations.AddField(
            model_name='medicine_type_usage',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Medicine'),
        ),
        migrations.AddField(
            model_name='medicine_type_usage',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine_type_usage',
            name='takingWay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.MedicineTakingWay'),
        ),
        migrations.AddField(
            model_name='medicine_type_usage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.MedicineType'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurement',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructionfactor',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.FactorOptions'),
        ),
        migrations.AddField(
            model_name='instructionfactor',
            name='medicine_taking_instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.MedicineTakingInstruction'),
        ),
        migrations.AddField(
            model_name='factoroptions',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Factor'),
        ),
        migrations.AddField(
            model_name='factoroptions',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factor',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasesymptom',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Disease'),
        ),
        migrations.AddField(
            model_name='diseasesymptom',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasesymptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Symptom'),
        ),
        migrations.AddField(
            model_name='diseasefactor',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Disease'),
        ),
        migrations.AddField(
            model_name='diseasefactor',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.FactorOptions'),
        ),
        migrations.AddField(
            model_name='diseasefactor',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasecategory',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disease',
            name='DiseaseCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.DiseaseCategory'),
        ),
        migrations.AddField(
            model_name='disease',
            name='pathogen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_disease_data.Pathogen'),
        ),
        migrations.AddField(
            model_name='disease',
            name='registralUserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
